default_stages: [pre-commit, pre-push]
default_language_version:
    python: python3.13
fail_fast: false
repos:
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.30.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-merge-conflict
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-toml
      - id: check-yaml
      - id: check-json

  - repo: local
    hooks:
      - id: typecheck
        name: typecheck
        entry: make typecheck
        language: system
        pass_filenames: false
        exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/|output/.*

  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        pass_filenames: false
        exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/|output/.*

  - repo: local
    hooks:
      - id: lint
        name: lint
        entry: make lint
        language: system
        pass_filenames: false
        exclude: tests(/\w*)*/functional/|tests/input|tests(/\w*)*data/|doc/|output/.*
